# Generated by Django 5.1.4 on 2025-06-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_alter_productvariant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Variant Name'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Restaurant Name'),
        ),
    ]
