# Generated by Django 5.1.4 on 2025-06-14 08:15

import restaurant.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_category_name_en_product_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='languages',
            field=restaurant.fields.MultipleChoiceArrayField(base_field=models.CharField(blank=True, choices=[('ar', 'Arabic'), ('he', 'Hebrew'), ('en', 'English')], max_length=100, null=True), blank=True, null=True, size=None),
        ),
    ]
