# Generated by Django 5.1.4 on 2025-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_socialmedia_info_alter_headerimage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('phone_number_1', 'Phone Number 1'), ('phone_number_2', 'Phone Number 2')], max_length=20, verbose_name='Platform'),
        ),
    ]
